#!/bin/zsh

# Build the shadow jar
./gradlew clean build shadowJar

# Check the exit code of the build command
if [[ $? -ne 0 ]]; then
    echo "Build failed, exiting."
    exit 1
fi

# Copy the jar to the current directory
cp -u build/libs/credit-updater.jar ./

# Run the jar file with the specified parameter
java -jar credit-updater.jar -i
